import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

export '../../features/settings/presentation/settings_provider.dart'
    show LocaleNotifier, localeProvider;

// Helper extension on BuildContext to quickly access translations
extension LocalizationContext on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this).translate(key);
  }

  bool get isRtl {
    return Directionality.of(this) == TextDirection.rtl;
  }
}

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static const supportedLocales = [
    Locale('en'),
    Locale('ar'),
  ];

  static const localizationsDelegates = [
    GlobalMaterialLocalizations.delegate,
    GlobalWidgetsLocalizations.delegate,
    GlobalCupertinoLocalizations.delegate,
  ];

  static AppLocalizations of(BuildContext context) {
    final locale = Localizations.localeOf(context);
    return AppLocalizations(locale);
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'dismiss': 'Dismiss',
      'replace_local_data': 'Replace local data',
      'restore_warning':
          'Warning: confirmation will replace all current local data.',
      'app_settings': 'Settings',
      'backup_preview': 'Backup preview',
      'restore_completed_successfully': 'Restore completed successfully.',
      'backup_created_successfully': 'Backup created successfully.',
      'restoring_safely': 'Restoring safely…',
      'validating_backup': 'Validating backup…',
      'creating_backup': 'Creating backup…',
      'select_backup': 'Select backup',
      'restore_desc2': 'Failed validation does not modify current data.',
      'restore_desc1':
          'Restore replaces all current local data; it does not merge records.',
      'restore': 'Restore',
      'create_backup': 'Create backup',
      'backup_warning':
          'Backup files are not encrypted and contain no credentials.',
      'backup_desc':
          'Create a complete copy of local business data and settings, then store it in a protected location.',
      'backup': 'Backup',
      'local_security_desc':
          'The app stores data locally for one device user. Physical device access implies access to app data subject to operating-system protections. No PIN, biometrics, or database encryption is implemented.',
      'local_security': 'Local security',
      'saved': 'Saved',
      'used_for_new_transactions_only': 'Used only for new transactions',
      'yer_per_sar': 'YER per SAR',
      'default_exchange_rate_desc': 'Default exchange rate: YER per 1 SAR',
      'profit': 'Profit',
      'revenue': 'Revenue',
      'monthly_performance': 'Monthly Performance',
      'expense': 'Expense',
      'payment': 'Payment',
      'project_overview': 'Project Overview',
      'month_jan': 'Jan',
      'month_feb': 'Feb',
      'month_mar': 'Mar',
      'month_apr': 'Apr',
      'month_may': 'May',
      'month_jun': 'Jun',
      'month_jul': 'Jul',
      'month_aug': 'Aug',
      'month_sep': 'Sep',
      'month_oct': 'Oct',
      'month_nov': 'Nov',
      'month_dec': 'Dec',
      'create': 'Create',
      'update': 'Update',
      'edit_expense': 'Edit Expense',
      'edit_payment': 'Edit Payment',
      'filter_by_status': 'Filter by Status',
      'err_project_not_found': 'Project not found',
      'err_enter_positive_rate': 'Enter a positive rate',
      'err_fixed_rate_required': 'Rate is required for fixed SAR policy',
      'fixed_exchange_rate_hint': 'e.g. 410.000000',
      'exchange_policy': 'Exchange policy',
      'app_title': "Construction ERP",
      'dashboard': "Dashboard",
      'clients': "Clients",
      'projects': "Projects",
      'reports': "Reports",
      'settings': "Settings",
      'language': "Language",
      'arabic': "العربية",
      'english': "English",
      'toggle_language': "عربي",
      'welcome_engineer': "Eng. Omar Badhman",
      'total_net_profit': "Total Net Profit",
      'currency': "SAR",
      'active': "Active",
      'completed': "Completed",
      'recent_activity': "Recent Activity",
      'view_all': "View All",
      'quick_actions': "Quick Actions",
      'new_project': "New project",
      'new_client': "New Client",
      'record_expense': "Record Expense",
      'record_payment': "Record Payment",
      'total_projects': "Total Projects",
      'financial_cards_title': "Financial Overview",
      'search_clients': "Search clients...",
      'add_client': "Add Client",
      'edit_client': "Edit Client",
      'client_details': "Client Details",
      'client_name': "Client Name",
      'phone': "Phone Number",
      'company': "Company Name",
      'save': "Save",
      'cancel': "Cancel",
      'no_clients': "No clients found",
      'saving': "Saving...",
      'delete_client': "Delete Client",
      'confirm_delete_client': "Are you sure you want to delete this client?",
      'delete': "Delete",
      'search_projects': "Search projects...",
      'add_project': "Add Project",
      'edit_project': "Edit Project",
      'project_details': "Project Details",
      'project_name': "Project Name",
      'project_name_required': "Project name *",
      'project_description': "Project description",
      'budget': "Budget",
      'contract_value': "Contract value",
      'contract_value_required': "Contract value *",
      'description': "Description",
      'start_date': "Start date",
      'end_date': "Expected end date",
      'select_client': "Select Client",
      'project_owner': "Project owner",
      'project_owner_required': "Project owner *",
      'select_project_owner': "Select project owner",
      'status': "Status",
      'project_status': "Project status",
      'select_project_status': "Select project status",
      'create_project': "Create project",
      'save_changes': "Save changes",
      'no_projects': "No projects found",
      'financials': "Financials",
      'milestones': "Milestones",
      'payments': "Payments",
      'expenses': "Expenses",
      'add_milestone': "Add Milestone",
      'add_payment': "Add payment",
      'new_payment': "New Payment",
      'add_expense': "Add expense",
      'new_expense': "New Expense",
      'progress': "Progress",
      'collected': "Collected",
      'payments_received': "Payments received",
      'remaining': "Remaining",
      'remaining_contract_value': "Remaining contract value",
      'net_cash_flow': "Net cash flow",
      'payments_exceeding_contract_value': "Payments exceeding contract value",
      'title': "Title",
      'amount': "Amount",
      'payment_amount': "Payment amount",
      'expense_amount': "Expense amount",
      'date': "Date",
      'date_received': "Date received",
      'expense_date': "Expense date",
      'due_date': "Due Date",
      'status_planning': "Planning",
      'status_active': "Active",
      'status_in_progress': "In progress",
      'status_completed': "Completed",
      'status_on_hold': "On hold",
      'status_cancelled': "Cancelled",
      'status_pending': "Pending",
      'status_overdue': "Overdue",
      'notes': "Notes",
      'category': "Category",
      'expense_category': "Expense category",
      'select_expense_category': "Select expense category",
      'expense_description': "Expense description",
      'payment_method': "Payment method",
      'exchange_rate': "Exchange rate",
      'save_payment': "Save payment",
      'delete_payment': "Delete payment",
      'restore_payment': "Restore payment",
      'total_payments_received': "Total payments received",
      'yemeni_rials_per_1_saudi_riyal': "Yemeni rials per 1 Saudi riyal",
      'save_expense': "Save expense",
      'delete_expense': "Delete expense",
      'restore_expense': "Restore expense",
      'total_expenses': "Total expenses",
      'err_select_project_owner': "Select a project owner.",
      'err_enter_project_name': "Enter the project name.",
      'err_valid_contract_value': "Enter a valid contract value.",
      'err_contract_value_gt_zero': "Contract value must be greater than zero.",
      'err_enter_payment_amount': "Enter the payment amount.",
      'err_payment_amount_gt_zero': "Payment amount must be greater than zero.",
      'err_select_project': "Select a project.",
      'err_select_expense_category': "Select an expense category.",
      'err_end_date_before_start':
          "End date cannot be earlier than start date.",
      'err_exchange_rate_gt_zero': "Exchange rate must be greater than zero.",
      'err_exchange_rate_max_decimals':
          "Exchange rate supports up to six decimal places.",
      'currency_label': "Currency",
      'select_currency': "Select currency",
      'yer': "Yemeni rial (YER)",
      'sar': "Saudi riyal (SAR)",
      'financial_summary': "Financial Summary",
      'total_budget': "Total Budget",
      'total_collected': "Total Collected",
      'profitability_rate': "Profitability Rate",
      'cash_flow_over_time': "Cash Flow Over Time",
      'no_reports_data': "No financial data available",
      'generate': "Generate Report",
      'report_type': "Report Type",
      'project_status_report': "Project Status",
      'financial_report': "Financial",
      'expense_report': "Expenses",
      'all_projects': "All Projects",
      'all_statuses': "All Statuses",
      'filter_start': "From",
      'filter_end': "To",
      'report_hint': "Choose a report type and filters, then tap Generate.",
      'income': "Income",
      'net': "Net",
      'grand_total': "Grand Total",
      'by_category': "By Category",
      'by_project': "By Project",
      'export': "Export",
      'no_data': "No data for the selected filters.",
      'retry': "Retry",
      'balance': "Balance",
      'profit_margin': "Profit Margin",
      'total_payments': "Total Payments",
      'milestones_progress': "Milestones",
      'project_detail': "Project Detail",
      'profitability': "Profitability",
      'tab_milestones': "Milestones",
      'tab_payments': "Payments",
      'tab_expenses': "Expenses",
      'no_milestones': "No milestones yet",
      'no_payments': "No payments yet",
      'no_expenses': "No expenses yet",
      'total': "Total",
      'due': "Due",
      'edit': "Edit",
      'backup_restore': "Backup & Restore",
      'settings_theme': "Theme",
      'fixed_rate': "Fixed Rate",
      'per_transaction': "Per Transaction",
      'cancel_project_delete': "Cancel",
      'delete_project': "Delete",
      'delete_project_title': "Delete project",
      'delete_project_content': "Are you sure you want to delete this project?",
      'error': "Error:",
      'due_date_required': "Due date is required",
      'financial_summary_tab': "Financial summary",
      'cash_surplus': "Cash surplus",
      'cash_balanced': "Cash balanced",
      'cash_deficit': "Cash deficit",
      'cash_surplus_detail': "Payments received exceed expenses by {amount}",
      'cash_balanced_detail': "Payments received equal expenses",
      'cash_deficit_detail': "Expenses exceed payments received by {amount}",
      'cost_overrun': "Project cost overrun",
      'cost_overrun_detail': "Expenses exceed the contract value by {amount}",
      'new_expense_title': "New expense",
      'edit_expense_title': "Edit expense",
      'expense_amount_required': "Expense amount *",
      'err_expense_amount_required': "Please enter the expense amount.",
      'err_expense_amount_positive':
          "Expense amount must be greater than zero.",
      'expense_date_required': "Expense date *",
      'select_date': "Select date",
      'exchange_rate_yer_sar': "Exchange rate (YER per SAR)",
      'err_rate_required_sar': "Exchange rate is required for SAR.",
      'expense_category_materials': "Materials",
      'expense_category_labor': "Labor",
      'expense_category_equipment': "Equipment",
      'expense_category_permits': "Permits",
      'expense_category_other': "Other",
      'new_payment_title': "New payment",
      'edit_payment_title': "Edit payment",
      'payment_amount_required': "Payment amount *",
      'err_payment_amount_required': "Please enter the payment amount.",
      'err_payment_amount_positive':
          "Payment amount must be greater than zero.",
      'payment_date_required': "Payment date *",
      'method': "Method",
      'payment_method_cash': "Cash",
      'payment_method_bank_transfer': "Bank transfer",
      'payment_method_cheque': "Cheque",
      'payment_method_other': "Other",
      'new_milestone_title': "New milestone",
      'edit_milestone_title': "Edit milestone",
      'milestone_title_required': "Milestone title *",
      'err_milestone_title_required': "Milestone title is required.",
      'milestone_description': "Milestone description",
      'milestone_due_date': "Expected completion date *",
      'milestone_status': "Milestone status",
      'milestone_status_pending': "Pending",
      'milestone_status_in_progress': "In progress",
      'milestone_status_completed': "Completed",
      'milestone_status_overdue': "Overdue",
      'create_milestone': "Create milestone",
      'add_new_client': "+ Add new client",
      'add_new_client_title': "Add new client",
      'name_required': "Name *",
      'client_name_required': "Client name *",
      'save_client': "Save client",
      'email_label': "Email",
      'address_label': "Address",
      'err_client_name_required': "Client name is required",
      'err_invalid_email': "Enter a valid email",
      'err_client_save_failed': "Failed to save the client. Please try again.",
      'err_client_create_failed': "Failed to create the client. Please try again.",
      'err_client_duplicate': "A client with this information may already exist.",
      'equivalent': "Equivalent",
      'financial_alert': "Financial Alert",
      'confirm_operation': "Confirm Operation",
      'warning_title': "Warning",
      'cross_currency_payment_warning': "A payment in a different currency is being entered.",
      'original_currency': "Original currency",
      'amount_label': "Amount",
      'exchange_rate_label': "Exchange rate",
      'value_after_conversion': "Value after conversion",
      'record_payment_question': "Do you want to record the payment?",
      'proceed': "Proceed",
      'expense_overcash_warning': "This expense will cause total expenses to exceed received payments.",
      'received_payments_label': "Received payments",
      'total_expenses_after_adding': "Total expenses after adding",
      'expected_deficit': "Expected deficit",
      'continue_question': "Do you want to continue?",
      'contract_value_locked': "The contract value cannot be edited after payments or expenses have been recorded. Use a contract amendment to add or change the value.",
      'contract_value_locked_short': "Contract value is locked",
      'amendment_label': "Contract amendment",
      'current_cash_balance': "Current cash balance",
      'wallet_balance_sar': "SAR wallet",
      'wallet_balance_yer': "YER wallet",
      'analytical_converted_value': "Converted value for reports",
      'analytical_value_disclaimer': "Analytical value only — based on the selected exchange rate",
      'analytical_exchange_rate': "Reporting exchange rate (YER per SAR)",
      'currency_transfer': "Currency transfer",
      'new_transfer_title': "Currency transfer",
      'transfer_from': "From",
      'transfer_to': "To",
      'transfer_amount': "Amount",
      'transfer_exchange_rate': "Exchange rate",
      'transfer_result_preview': "Result",
      'transfer_date': "Transfer date",
      'save_transfer': "Save transfer",
      'insufficient_balance_title': "Insufficient balance",
      'insufficient_balance_body': "There is not enough balance in this currency.",
      'current_balance_label': "Current balance",
      'expense_value_label': "Expense value",
      'deficit_label': "Deficit",
      'convert_currency_option': "Convert currency",
      'external_funding_option': "External funding",
      'cancel_option': "Cancel",
      'no_transfers': "No transfers yet"
    },
    'ar': {
      'backup_warning':
          "ملفات النسخ الاحتياطي غير مشفرة ولا تحتوي على بيانات اعتماد.",
      'financial_summary_tab': "الملخص المالي",
      'cash_surplus': "فائض نقدي",
      'cash_balanced': "متعادل نقديًا",
      'cash_deficit': "عجز نقدي",
      'cash_surplus_detail':
          "الدفعات المستلمة تتجاوز المصروفات بمقدار {amount}",
      'cash_balanced_detail': "الدفعات المستلمة تساوي المصروفات",
      'cash_deficit_detail':
          "المصروفات تتجاوز الدفعات المستلمة بمقدار {amount}",
      'cost_overrun': "تجاوز في تكلفة المشروع",
      'cost_overrun_detail': "المصروفات تجاوزت قيمة العقد بمقدار {amount}",
      'new_expense_title': "مصروف جديد",
      'edit_expense_title': "تعديل المصروف",
      'expense_amount_required': "مبلغ المصروف *",
      'err_expense_amount_required': "يرجى إدخال مبلغ المصروف.",
      'err_expense_amount_positive': "يجب أن يكون مبلغ المصروف أكبر من صفر.",
      'expense_date_required': "تاريخ المصروف *",
      'select_date': "اختر التاريخ",
      'exchange_rate_yer_sar': "سعر الصرف (ريال يمني لكل ريال سعودي)",
      'err_rate_required_sar': "سعر الصرف مطلوب للريال السعودي.",
      'expense_category_materials': "مواد",
      'expense_category_labor': "أجور العمال",
      'expense_category_equipment': "معدات",
      'expense_category_permits': "تصاريح",
      'expense_category_other': "أخرى",
      'new_payment_title': "دفعة جديدة",
      'edit_payment_title': "تعديل الدفعة",
      'payment_amount_required': "مبلغ الدفعة *",
      'err_payment_amount_required': "يرجى إدخال مبلغ الدفعة.",
      'err_payment_amount_positive': "يجب أن يكون مبلغ الدفعة أكبر من صفر.",
      'payment_date_required': "تاريخ استلام الدفعة *",
      'method': "طريقة الدفع",
      'payment_method_cash': "نقدًا",
      'payment_method_bank_transfer': "تحويل بنكي",
      'payment_method_cheque': "شيك",
      'payment_method_other': "أخرى",
      'new_milestone_title': "مرحلة جديدة",
      'edit_milestone_title': "تعديل المرحلة",
      'milestone_title_required': "اسم المرحلة *",
      'err_milestone_title_required': "اسم المرحلة مطلوب.",
      'milestone_description': "وصف المرحلة",
      'milestone_due_date': "تاريخ الانتهاء المتوقع *",
      'milestone_status': "حالة المرحلة",
      'milestone_status_pending': "قيد الانتظار",
      'milestone_status_in_progress': "قيد التنفيذ",
      'milestone_status_completed': "مكتملة",
      'milestone_status_overdue': "متأخرة",
      'create_milestone': "إنشاء المرحلة",
      'filter_by_status': 'تصفية حسب الحالة',
      'err_project_not_found': 'المشروع غير موجود',
      'err_enter_positive_rate': 'يرجى إدخال سعر صرف موجب',
      'err_fixed_rate_required': 'سعر الصرف مطلوب لسياسة السعر الثابت',
      'fixed_exchange_rate_hint': 'مثال: 410.000000',
      'exchange_policy': 'سياسة الصرف',
      'app_title': "نظام إدارة المقاولات",
      'dashboard': "لوحة التحكم",
      'clients': "العملاء",
      'projects': "المشاريع",
      'reports': "التقارير",
      'settings': "الإعدادات",
      'language': "اللغة",
      'arabic': "العربية",
      'english': "English",
      'toggle_language': "English",
      'welcome_engineer': "م. عمر بادحمان",
      'total_net_profit': "صافي الأرباح الإجمالية",
      'currency': "ريال",
      'profit': "الربح",
      'revenue': "الإيرادات",
      'monthly_performance': "الأداء الشهري",
      'expense': "مصروف",
      'payment': "دفعة",
      'project_overview': "نظرة عامة على المشاريع",
      'month_jan': "يناير",
      'month_feb': "فبراير",
      'month_mar': "مارس",
      'month_apr': "أبريل",
      'month_may': "مايو",
      'month_jun': "يونيو",
      'month_jul': "يوليو",
      'month_aug': "أغسطس",
      'month_sep': "سبتمبر",
      'month_oct': "أكتوبر",
      'month_nov': "نوفمبر",
      'month_dec': "ديسمبر",
      'active': "نشط",
      'completed': "مكتمل",
      'recent_activity': "آخر الأنشطة",
      'view_all': "عرض الكل",
      'quick_actions': "إجراءات سريعة",
      'new_project': "مشروع جديد",
      'new_client': "عميل جديد",
      'record_expense': "تسجيل مصروف",
      'record_payment': "تسجيل دفعة",
      'total_projects': "إجمالي المشاريع",
      'financial_cards_title': "الملخص المالي العام",
      'search_clients': "البحث عن العملاء...",
      'add_client': "إضافة عميل",
      'edit_client': "تعديل عميل",
      'client_details': "تفاصيل العميل",
      'client_name': "اسم العميل",
      'phone': "رقم الهاتف",
      'company': "اسم الشركة",
      'save': "حفظ",
      'cancel': "إلغاء",
      'no_clients': "لم يتم العثور على عملاء",
      'saving': "جاري الحفظ...",
      'delete_client': "حذف العميل",
      'confirm_delete_client': "هل أنت متأكد من رغبتك في حذف هذا العميل؟",
      'delete': "حذف",
      'search_projects': "البحث عن المشاريع...",
      'add_project': "إضافة مشروع",
      'edit_project': "تعديل مشروع",
      'project_details': "تفاصيل المشروع",
      'project_name': "اسم المشروع",
      'project_name_required': "اسم المشروع *",
      'project_description': "وصف المشروع",
      'budget': "الميزانية",
      'contract_value': "قيمة العقد",
      'contract_value_required': "قيمة العقد *",
      'description': "الوصف",
      'start_date': "تاريخ البدء",
      'end_date': "تاريخ الانتهاء المتوقع",
      'select_client': "اختر العميل",
      'project_owner': "صاحب المشروع",
      'project_owner_required': "صاحب المشروع *",
      'select_project_owner': "اختر صاحب المشروع",
      'status': "الحالة",
      'project_status': "حالة المشروع",
      'select_project_status': "اختر حالة المشروع",
      'create_project': "إنشاء المشروع",
      'save_changes': "حفظ التعديلات",
      'no_projects': "لم يتم العثور على مشاريع",
      'financials': "المالية",
      'milestones': "المراحل والمحطات",
      'payments': "المدفوعات",
      'expenses': "المصروفات",
      'add_milestone': "إضافة مرحلة",
      'add_payment': "إضافة دفعة",
      'new_payment': "دفعة جديدة",
      'add_expense': "إضافة مصروف",
      'new_expense': "مصروف جديد",
      'progress': "نسبة الإنجاز",
      'collected': "المحصل",
      'payments_received': "الدفعات المستلمة",
      'remaining': "المتبقي",
      'remaining_contract_value': "المتبقي من قيمة العقد",
      'net_cash_flow': "صافي التدفق النقدي",
      'payments_exceeding_contract_value': "دفعات زائدة عن قيمة العقد",
      'title': "العنوان",
      'amount': "المبلغ",
      'payment_amount': "مبلغ الدفعة",
      'expense_amount': "مبلغ المصروف",
      'date': "التاريخ",
      'date_received': "تاريخ الاستلام",
      'expense_date': "تاريخ المصروف",
      'due_date': "تاريخ الاستحقاق",
      'status_planning': "قيد التخطيط",
      'status_active': "نشط",
      'status_in_progress': "قيد التنفيذ",
      'status_completed': "مكتمل",
      'status_on_hold': "معلّق",
      'status_cancelled': "ملغي",
      'status_pending': "قيد الانتظار",
      'status_overdue': "متأخر",
      'notes': "ملاحظات",
      'category': "الفئة",
      'expense_category': "فئة المصروف",
      'select_expense_category': "اختر فئة المصروف",
      'expense_description': "وصف المصروف",
      'payment_method': "طريقة الدفع",
      'exchange_rate': "سعر الصرف",
      'save_payment': "حفظ الدفعة",
      'delete_payment': "حذف الدفعة",
      'restore_payment': "استعادة الدفعة",
      'total_payments_received': "إجمالي الدفعات المستلمة",
      'yemeni_rials_per_1_saudi_riyal':
          "عدد الريالات اليمنية مقابل 1 ريال سعودي",
      'save_expense': "حفظ المصروف",
      'delete_expense': "حذف المصروف",
      'restore_expense': "استعادة المصروف",
      'total_expenses': "إجمالي المصروفات",
      'err_select_project_owner': "يرجى اختيار صاحب المشروع.",
      'err_enter_project_name': "يرجى إدخال اسم المشروع.",
      'err_valid_contract_value': "يرجى إدخال قيمة عقد صحيحة.",
      'err_contract_value_gt_zero': "يجب أن تكون قيمة العقد أكبر من صفر.",
      'err_enter_payment_amount': "يرجى إدخال مبلغ الدفعة.",
      'err_payment_amount_gt_zero': "يجب أن يكون مبلغ الدفعة أكبر من صفر.",
      'err_select_project': "يرجى اختيار المشروع.",
      'err_select_expense_category': "يرجى اختيار فئة المصروف.",
      'err_end_date_before_start':
          "تاريخ الانتهاء لا يمكن أن يسبق تاريخ البدء.",
      'err_exchange_rate_gt_zero': "سعر الصرف يجب أن يكون أكبر من صفر.",
      'err_exchange_rate_max_decimals':
          "لا يمكن استخدام أكثر من ست خانات عشرية في سعر الصرف.",
      'currency_label': "العملة",
      'select_currency': "اختر العملة",
      'yer': "الريال اليمني (YER)",
      'sar': "الريال السعودي (SAR)",
      'financial_summary': "الملخص المالي العام",
      'total_budget': "إجمالي الميزانيات",
      'total_collected': "إجمالي المقبوضات",
      'profitability_rate': "معدل الربحية",
      'cash_flow_over_time': "التدفقات النقدية مع الوقت",
      'no_reports_data': "لا توجد بيانات مالية متاحة",
      'generate': "إنشاء التقرير",
      'report_type': "نوع التقرير",
      'project_status_report': "حالة المشاريع",
      'financial_report': "المالية",
      'expense_report': "المصروفات",
      'all_projects': "جميع المشاريع",
      'all_statuses': "جميع الحالات",
      'filter_start': "من",
      'filter_end': "إلى",
      'report_hint': "اختر نوع التقرير والفلاتر، ثم اضغط إنشاء.",
      'income': "الدخل",
      'net': "الصافي",
      'grand_total': "الإجمالي الكلي",
      'by_category': "حسب الفئة",
      'by_project': "حسب المشروع",
      'export': "تصدير",
      'no_data': "لا توجد بيانات للفلاتر المختارة.",
      'retry': "إعادة المحاولة",
      'balance': "الرصيد",
      'profit_margin': "هامش الربح",
      'total_payments': "إجمالي المدفوعات",
      'milestones_progress': "المراحل",
      'project_detail': "تفاصيل المشروع",
      'profitability': "الربحية",
      'tab_milestones': "المراحل",
      'tab_payments': "المدفوعات",
      'tab_expenses': "المصروفات",
      'no_milestones': "لا توجد مراحل بعد",
      'no_payments': "لا توجد مدفوعات بعد",
      'no_expenses': "لا توجد مصروفات بعد",
      'total': "الإجمالي",
      'due': "الاستحقاق",
      'edit': "تعديل",
      'backup_restore': "النسخ الاحتياطي والاستعادة",
      'settings_theme': "المظهر",
      'fixed_rate': "سعر ثابت",
      'per_transaction': "حسب المعاملة",
      'cancel_project_delete': "إلغاء",
      'delete_project': "حذف",
      'delete_project_title': "حذف المشروع",
      'delete_project_content': "هل أنت متأكد من رغبتك في حذف هذا المشروع؟",
      'error': "خطأ:",
      'due_date_required': "تاريخ الاستحقاق مطلوب",
      'add_new_client': "+ إضافة عميل جديد",
      'add_new_client_title': "إضافة عميل جديد",
      'name_required': "الاسم *",
      'client_name_required': "اسم العميل *",
      'save_client': "حفظ العميل",
      'email_label': "البريد الإلكتروني",
      'address_label': "العنوان",
      'err_client_name_required': "اسم العميل مطلوب",
      'err_invalid_email': "أدخل بريداً إلكترونياً صحيحاً",
      'err_client_save_failed': "فشل حفظ العميل. يرجى المحاولة مرة أخرى.",
      'err_client_create_failed': "فشل إنشاء العميل. يرجى المحاولة مرة أخرى.",
      'err_client_duplicate': "قد تكون بيانات هذا العميل موجودة بالفعل.",
      'equivalent': "المكافئ",
      'financial_alert': "تنبيه مالي",
      'confirm_operation': "تأكيد العملية",
      'warning_title': "تحذير",
      'cross_currency_payment_warning': "تم إدخال دفعة بعملة مختلفة.",
      'original_currency': "العملة الأصلية",
      'amount_label': "المبلغ",
      'exchange_rate_label': "سعر الصرف",
      'value_after_conversion': "القيمة بعد التحويل",
      'record_payment_question': "هل تريد تسجيل الدفعة؟",
      'proceed': "متابعة",
      'expense_overcash_warning': "هذا المصروف سيؤدي إلى تجاوز الدفعات المستلمة.",
      'received_payments_label': "الدفعات المستلمة",
      'total_expenses_after_adding': "إجمالي المصروفات بعد الإضافة",
      'expected_deficit': "العجز المتوقع",
      'continue_question': "هل تريد المتابعة؟",
      'contract_value_locked': "لا يمكن تعديل قيمة العقد بعد تسجيل دفعات أو مصروفات. استخدم تعديل العقد لإضافة أو تغيير القيمة.",
      'contract_value_locked_short': "قيمة العقد مقفلة",
      'amendment_label': "تعديل العقد",
      'current_cash_balance': "الرصيد النقدي الحالي",
      'wallet_balance_sar': "محفظة الريال السعودي",
      'wallet_balance_yer': "محفظة الريال اليمني",
      'analytical_converted_value': "القيمة المحولة للتقارير",
      'analytical_value_disclaimer': "قيمة تحليلية فقط — بناءً على سعر الصرف المحدد",
      'analytical_exchange_rate': "سعر الصرف للتقارير (ريال يمني لكل ريال سعودي)",
      'currency_transfer': "تحويل عملة",
      'new_transfer_title': "تحويل عملة",
      'transfer_from': "من",
      'transfer_to': "إلى",
      'transfer_amount': "المبلغ",
      'transfer_exchange_rate': "سعر الصرف",
      'transfer_result_preview': "النتيجة",
      'transfer_date': "تاريخ التحويل",
      'save_transfer': "حفظ التحويل",
      'insufficient_balance_title': "تنبيه مالي",
      'insufficient_balance_body': "لا يوجد رصيد كافي بهذه العملة.",
      'current_balance_label': "الرصيد الحالي",
      'expense_value_label': "قيمة المصروف",
      'deficit_label': "العجز",
      'convert_currency_option': "تحويل عملة",
      'external_funding_option': "تمويل خارجي",
      'cancel_option': "إلغاء",
      'no_transfers': "لا توجد تحويلات بعد"
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}
